fix(example): handle redirects in TanStack router
marbemac/ssrx pull request #33
Opened 2024-05-22 02:50 UTC by drew-harris

This PR fixes the doRedirect=true example in the `examples/tanstack-router-simple` folder, as well as just being a general fix for anyone trying to use redirects in Tanstack Router.

2024-05-22 02:53 UTC, drew-harris commented
fixes #34

2024-05-22 13:04 UTC, marbemac requested changes
Thanks for this!

Only other request is I think we can tidy up the redirect page a little bit now - just removing the "it doesn't work on server" caveat, and adding a link to show the server-side redirect. Something along these lines, what do you think?

```tsx
function RedirectComponent() {
  return (
    <div>
      <h2>Redirect</h2>

      <p>
        This route redirects if the `doRedirect=true` search param is present. Should support redirect on the server as
        well on first load when relevant.
      </p>

      <p>
        <Link to="/redirect" search={{ doRedirect: true }} className="text-blue-700">
          Client Side Redirect
        </Link>
      </p>

      <p>
        <a href="/redirect?doRedirect=true" className="text-blue-700">
          Server Side Redirect
        </a>
      </p>
    </div>
  );
}
```

2024-05-22 23:58 UTC, drew-harris commented
Good catch on the query params. Pushed new updates containing the exact feedback you gave.

2024-05-23 13:18 UTC, marbemac approved these changes
thank you ❤️

2024-05-23 13:19 UTC, merged